services:
  db:
    container_name: postgres_container
    image: postgres:15
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mathsketch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/postgresql/data

volumes:
  postgres_data:

  api:
    container_name: mathsketch_container
    build: .
    env_file:
      - .env.docker
    depends_on:
      - db
